logging:
  level:
    root: error
    com.hw8: error
  file: logs/${spring.application.name}.log
server:
  port: 8088
spring:
  application:
    name: hw8-test  
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  devtools:
    restart:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
